version: '3'
services:

  backend:
    restart: always
    depends_on:
    - redis
    container_name: backend
    build:
      context: ../back
    ports:
    - "5001:5001"
    networks:
    - docker_network
    environment:
    - PYTHONUNBUFFERED=0

  redis:
    container_name: redis
    image: "redislabs/rejson:latest"
    volumes:
        - redis:/data
    ports:
      - "6379:6379"
    networks:
    - docker_network

  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ../front     
    ports:
    - "5000:5000"
    networks:
    - docker_network

networks:
  docker_network:
    driver: bridge
volumes:
  redis:
    driver: local
    driver_opts:
      type: ''
      o: 'bind'
      device: '/home/panda/project/data/redis'