version: '3'
services:

  backend:
    depends_on:
    - redis
    - db
    container_name: backend
    build:
      context: ../back
    ports:
    - "5001:5001"
    networks:
    - docker_network
    environment:
    - PYTHONUNBUFFERED=0

  redis:
    container_name: redis
    image: "redislabs/rejson:latest"
    volumes:
        - ../data:/data
    networks:
    - docker_network


  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ../front
        
    ports:
    - "5000:5000"
    networks:
    - docker_network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ../data/postgres:/var/lib/postgresql
    networks:
    - docker_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
    - docker_network

networks:
  docker_network:
    driver: bridge
